/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as PrivateTravelRouteImport } from './routes/private-travel'
import { Route as LodgesRouteImport } from './routes/lodges'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdventuresRouteImport } from './routes/adventures'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LodgesSlugRouteImport } from './routes/lodges.$slug'
import { Route as JourneysSlugRouteImport } from './routes/journeys.$slug'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ItinerariesSlugRouteImport } from './routes/itineraries.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BookingSuccessRouteImport } from './routes/booking.success'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin/subscribers'
import { Route as AuthenticatedAdminPrivateTravelRouteImport } from './routes/_authenticated/admin/private-travel'
import { Route as AuthenticatedAdminPlanningGuideRouteImport } from './routes/_authenticated/admin/planning-guide'
import { Route as AuthenticatedAdminJournalRouteImport } from './routes/_authenticated/admin/journal'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin/enquiries'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin/bookings'
import { Route as AuthenticatedAdminAdventuresRouteImport } from './routes/_authenticated/admin/adventures'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAdminPagesPageRouteImport } from './routes/_authenticated/admin/pages.$page'
import { Route as AuthenticatedAdminContentTableRouteImport } from './routes/_authenticated/admin/content.$table'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateTravelRoute = PrivateTravelRouteImport.update({
  id: '/private-travel',
  path: '/private-travel',
  getParentRoute: () => rootRouteImport,
} as any)
const LodgesRoute = LodgesRouteImport.update({
  id: '/lodges',
  path: '/lodges',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresRoute = AdventuresRouteImport.update({
  id: '/adventures',
  path: '/adventures',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LodgesSlugRoute = LodgesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LodgesRoute,
} as any)
const JourneysSlugRoute = JourneysSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JourneysRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const ItinerariesSlugRoute = ItinerariesSlugRouteImport.update({
  id: '/itineraries/$slug',
  path: '/itineraries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPrivateTravelRoute =
  AuthenticatedAdminPrivateTravelRouteImport.update({
    id: '/private-travel',
    path: '/private-travel',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlanningGuideRoute =
  AuthenticatedAdminPlanningGuideRouteImport.update({
    id: '/planning-guide',
    path: '/planning-guide',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminJournalRoute =
  AuthenticatedAdminJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdventuresRoute =
  AuthenticatedAdminAdventuresRouteImport.update({
    id: '/adventures',
    path: '/adventures',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminPagesPageRoute =
  AuthenticatedAdminPagesPageRouteImport.update({
    id: '/pages/$page',
    path: '/pages/$page',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContentTableRoute =
  AuthenticatedAdminContentTableRouteImport.update({
    id: '/content/$table',
    path: '/content/$table',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adventures': typeof AdventuresRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRouteWithChildren
  '/journeys': typeof JourneysRouteWithChildren
  '/lodges': typeof LodgesRouteWithChildren
  '/private-travel': typeof PrivateTravelRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/book/$slug': typeof BookSlugRoute
  '/booking/success': typeof BookingSuccessRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journeys/$slug': typeof JourneysSlugRoute
  '/lodges/$slug': typeof LodgesSlugRoute
  '/admin/adventures': typeof AuthenticatedAdminAdventuresRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/planning-guide': typeof AuthenticatedAdminPlanningGuideRoute
  '/admin/private-travel': typeof AuthenticatedAdminPrivateTravelRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/content/$table': typeof AuthenticatedAdminContentTableRoute
  '/admin/pages/$page': typeof AuthenticatedAdminPagesPageRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adventures': typeof AdventuresRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRouteWithChildren
  '/journeys': typeof JourneysRouteWithChildren
  '/lodges': typeof LodgesRouteWithChildren
  '/private-travel': typeof PrivateTravelRoute
  '/testimonials': typeof TestimonialsRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/success': typeof BookingSuccessRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journeys/$slug': typeof JourneysSlugRoute
  '/lodges/$slug': typeof LodgesSlugRoute
  '/admin/adventures': typeof AuthenticatedAdminAdventuresRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/planning-guide': typeof AuthenticatedAdminPlanningGuideRoute
  '/admin/private-travel': typeof AuthenticatedAdminPrivateTravelRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/content/$table': typeof AuthenticatedAdminContentTableRoute
  '/admin/pages/$page': typeof AuthenticatedAdminPagesPageRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/adventures': typeof AdventuresRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRouteWithChildren
  '/journeys': typeof JourneysRouteWithChildren
  '/lodges': typeof LodgesRouteWithChildren
  '/private-travel': typeof PrivateTravelRoute
  '/testimonials': typeof TestimonialsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/book/$slug': typeof BookSlugRoute
  '/booking/success': typeof BookingSuccessRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journeys/$slug': typeof JourneysSlugRoute
  '/lodges/$slug': typeof LodgesSlugRoute
  '/_authenticated/admin/adventures': typeof AuthenticatedAdminAdventuresRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/_authenticated/admin/planning-guide': typeof AuthenticatedAdminPlanningGuideRoute
  '/_authenticated/admin/private-travel': typeof AuthenticatedAdminPrivateTravelRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/content/$table': typeof AuthenticatedAdminContentTableRoute
  '/_authenticated/admin/pages/$page': typeof AuthenticatedAdminPagesPageRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adventures'
    | '/auth'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/journal'
    | '/journeys'
    | '/lodges'
    | '/private-travel'
    | '/testimonials'
    | '/admin'
    | '/book/$slug'
    | '/booking/success'
    | '/destinations/$slug'
    | '/itineraries/$slug'
    | '/journal/$slug'
    | '/journeys/$slug'
    | '/lodges/$slug'
    | '/admin/adventures'
    | '/admin/bookings'
    | '/admin/enquiries'
    | '/admin/journal'
    | '/admin/planning-guide'
    | '/admin/private-travel'
    | '/admin/subscribers'
    | '/admin/'
    | '/admin/content/$table'
    | '/admin/pages/$page'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adventures'
    | '/auth'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/journal'
    | '/journeys'
    | '/lodges'
    | '/private-travel'
    | '/testimonials'
    | '/book/$slug'
    | '/booking/success'
    | '/destinations/$slug'
    | '/itineraries/$slug'
    | '/journal/$slug'
    | '/journeys/$slug'
    | '/lodges/$slug'
    | '/admin/adventures'
    | '/admin/bookings'
    | '/admin/enquiries'
    | '/admin/journal'
    | '/admin/planning-guide'
    | '/admin/private-travel'
    | '/admin/subscribers'
    | '/admin'
    | '/admin/content/$table'
    | '/admin/pages/$page'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/adventures'
    | '/auth'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/journal'
    | '/journeys'
    | '/lodges'
    | '/private-travel'
    | '/testimonials'
    | '/_authenticated/admin'
    | '/book/$slug'
    | '/booking/success'
    | '/destinations/$slug'
    | '/itineraries/$slug'
    | '/journal/$slug'
    | '/journeys/$slug'
    | '/lodges/$slug'
    | '/_authenticated/admin/adventures'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/journal'
    | '/_authenticated/admin/planning-guide'
    | '/_authenticated/admin/private-travel'
    | '/_authenticated/admin/subscribers'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/content/$table'
    | '/_authenticated/admin/pages/$page'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdventuresRoute: typeof AdventuresRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FaqRoute: typeof FaqRoute
  JournalRoute: typeof JournalRouteWithChildren
  JourneysRoute: typeof JourneysRouteWithChildren
  LodgesRoute: typeof LodgesRouteWithChildren
  PrivateTravelRoute: typeof PrivateTravelRoute
  TestimonialsRoute: typeof TestimonialsRoute
  BookSlugRoute: typeof BookSlugRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  ItinerariesSlugRoute: typeof ItinerariesSlugRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-travel': {
      id: '/private-travel'
      path: '/private-travel'
      fullPath: '/private-travel'
      preLoaderRoute: typeof PrivateTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lodges': {
      id: '/lodges'
      path: '/lodges'
      fullPath: '/lodges'
      preLoaderRoute: typeof LodgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures': {
      id: '/adventures'
      path: '/adventures'
      fullPath: '/adventures'
      preLoaderRoute: typeof AdventuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lodges/$slug': {
      id: '/lodges/$slug'
      path: '/$slug'
      fullPath: '/lodges/$slug'
      preLoaderRoute: typeof LodgesSlugRouteImport
      parentRoute: typeof LodgesRoute
    }
    '/journeys/$slug': {
      id: '/journeys/$slug'
      path: '/$slug'
      fullPath: '/journeys/$slug'
      preLoaderRoute: typeof JourneysSlugRouteImport
      parentRoute: typeof JourneysRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/itineraries/$slug': {
      id: '/itineraries/$slug'
      path: '/itineraries/$slug'
      fullPath: '/itineraries/$slug'
      preLoaderRoute: typeof ItinerariesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/private-travel': {
      id: '/_authenticated/admin/private-travel'
      path: '/private-travel'
      fullPath: '/admin/private-travel'
      preLoaderRoute: typeof AuthenticatedAdminPrivateTravelRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/planning-guide': {
      id: '/_authenticated/admin/planning-guide'
      path: '/planning-guide'
      fullPath: '/admin/planning-guide'
      preLoaderRoute: typeof AuthenticatedAdminPlanningGuideRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/journal': {
      id: '/_authenticated/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AuthenticatedAdminJournalRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/adventures': {
      id: '/_authenticated/admin/adventures'
      path: '/adventures'
      fullPath: '/admin/adventures'
      preLoaderRoute: typeof AuthenticatedAdminAdventuresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/pages/$page': {
      id: '/_authenticated/admin/pages/$page'
      path: '/pages/$page'
      fullPath: '/admin/pages/$page'
      preLoaderRoute: typeof AuthenticatedAdminPagesPageRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content/$table': {
      id: '/_authenticated/admin/content/$table'
      path: '/content/$table'
      fullPath: '/admin/content/$table'
      preLoaderRoute: typeof AuthenticatedAdminContentTableRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdventuresRoute: typeof AuthenticatedAdminAdventuresRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminJournalRoute: typeof AuthenticatedAdminJournalRoute
  AuthenticatedAdminPlanningGuideRoute: typeof AuthenticatedAdminPlanningGuideRoute
  AuthenticatedAdminPrivateTravelRoute: typeof AuthenticatedAdminPrivateTravelRoute
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminContentTableRoute: typeof AuthenticatedAdminContentTableRoute
  AuthenticatedAdminPagesPageRoute: typeof AuthenticatedAdminPagesPageRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdventuresRoute: AuthenticatedAdminAdventuresRoute,
    AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
    AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
    AuthenticatedAdminJournalRoute: AuthenticatedAdminJournalRoute,
    AuthenticatedAdminPlanningGuideRoute: AuthenticatedAdminPlanningGuideRoute,
    AuthenticatedAdminPrivateTravelRoute: AuthenticatedAdminPrivateTravelRoute,
    AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminContentTableRoute: AuthenticatedAdminContentTableRoute,
    AuthenticatedAdminPagesPageRoute: AuthenticatedAdminPagesPageRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface JourneysRouteChildren {
  JourneysSlugRoute: typeof JourneysSlugRoute
}

const JourneysRouteChildren: JourneysRouteChildren = {
  JourneysSlugRoute: JourneysSlugRoute,
}

const JourneysRouteWithChildren = JourneysRoute._addFileChildren(
  JourneysRouteChildren,
)

interface LodgesRouteChildren {
  LodgesSlugRoute: typeof LodgesSlugRoute
}

const LodgesRouteChildren: LodgesRouteChildren = {
  LodgesSlugRoute: LodgesSlugRoute,
}

const LodgesRouteWithChildren =
  LodgesRoute._addFileChildren(LodgesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdventuresRoute: AdventuresRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FaqRoute: FaqRoute,
  JournalRoute: JournalRouteWithChildren,
  JourneysRoute: JourneysRouteWithChildren,
  LodgesRoute: LodgesRouteWithChildren,
  PrivateTravelRoute: PrivateTravelRoute,
  TestimonialsRoute: TestimonialsRoute,
  BookSlugRoute: BookSlugRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  ItinerariesSlugRoute: ItinerariesSlugRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
